name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up networking for Go modules
        run: |
          # Ensure we can reach Go module proxy
          curl -f https://proxy.golang.org/ || echo "Go proxy check failed"

      - name: Run flake check
        run: nix flake check --impure
